apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    release: {{ .Release.Name }}
{{- toYaml .Values.labels | nindent 4 }}
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.controller.port }}
